name = "Effects"
uuid = "f5584ebd-f602-4afe-9d3f-e139a3298ec2"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
